local_costmap:
    global_frame: odom
    robot_base_frame: base_link
    plugins:
        - {name: rolling_layer, type: "rolling_layer::RollingLayer"}
        # - {name: obstacle_2d_layer, type: "costmap_2d::ObstacleLayer"}
    publish_frequency: 5.0
    footprint: [[-0.24,0.32],[0.72,0.32],[0.72,-0.32],[-0.24,-0.32]]
    width: 20
    height: 20
    origin_x: -10
    origin_y: -10
    update_frequency: 10
    track_unknown_space: false
    unknown_cost_value: 30
    static_map: false
    rolling_window: true
    resolution: 0.1
    inflation_radius: 0.4


rolling_layer:
    topic: "/move_base_flex/global_costmap/costmap"

# obstacle_2d_layer:
#     observation_sources: scan
#     scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}